version: 2.0

jobs:
  compile:
    docker:
      - image: circleci/clojure:lein-2.7.1
    working_directory: ~/realworld-backend
    steps:
      - checkout
      - attach_workspace:
          at: ~/realworld-backend
      - restore_cache:
          keys:
            - realworld-backend-{{ checksum "project.clj" }}-{{ checksum "environments/development/project.clj" }}
            - polylith-cache-
      - run:
          name: Print workspace info
          command: lein polylith info
      - run:
          name: Compile changed projects
          command: lein polylith compile
      - save_cache:
          key: realworld-backend-{{ checksum "project.clj" }}-{{ checksum "environments/development/project.clj" }}
          paths:
            - ~/.m2
            - ~/.lein
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    docker:
      - image: circleci/clojure:lein-2.7.1
    working_directory: ~/realworld-backend
    steps:
      - attach_workspace:
          at: ~/realworld-backend
      - restore_cache:
          keys:
            - realworld-backend-{{ checksum "project.clj" }}-{{ checksum "environments/development/project.clj" }}
            - polylith-cache-
      - run:
          name: Test changed projects
          command: lein polylith test -compile
      - persist_to_workspace:
          root: .
          paths:
            - .

  build:
    docker:
      - image: circleci/clojure:lein-2.7.1
    working_directory: ~/realworld-backend
    steps:
      - attach_workspace:
          at: ~/realworld-backend
      - restore_cache:
          keys:
            - realworld-backend-{{ checksum "project.clj" }}-{{ checksum "environments/development/project.clj" }}
            - polylith-cache-
      - run:
          name: Build changed projects
          command: lein polylith build -compile -test -success
      - persist_to_workspace:
          root: .
          paths:
            - .

  artifacts:
    machine:
      enabled: true
    working_directory: ~/realworld-backend
    steps:
      - attach_workspace:
          at: ~/realworld-backend
      - restore_cache:
          keys:
            - realworld-backend-{{ checksum "project.clj" }}-{{ checksum "environments/development/project.clj" }}
            - polylith-cache-
      - run:
          name: Find built systems, print to console and move to artifacts
          command: |
            mkdir -p artifacts

            built_systems=`lein polylith changes s`

            echo $built_systems

            for system in $built_systems; do
              artifact="systems/""$system""/target/""$system"".war"
              cp $artifact artifacts/.
            done
      - store_artifacts:
          path: artifacts
          destination: artifacts
      - persist_to_workspace:
          root: .
          paths:
            - .

  success:
    docker:
      - image: circleci/clojure:lein-2.7.1
    working_directory: ~/realworld-backend
    steps:
      - attach_workspace:
          at: ~/realworld-backend
      - restore_cache:
          keys:
            - realworld-backend-{{ checksum "project.clj" }}-{{ checksum "environments/development/project.clj" }}
            - polylith-cache-
      - run:
          name: Set new :last-successful-build
          command: lein polylith success
      - save_cache:
          key: polylith-cache-{{ checksum ".polylith/time.local.edn" }}
          paths:
            - ~/realworld-backend/.polylith

workflows:
  version: 2
  test-build-success:
    jobs:
      - compile
      - test:
          requires:
            - compile
      - build:
          requires:
            - test
      - artifacts:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - develop
      - success:
          requires:
            - artifacts
          filters:
            branches:
              only:
                - master
                - develop
